### ISSUE TITLE
[feature request] Compatibility with Intel

### ISSUE THREAD

**Issue by ethanuppal** [CraftSpider/boxing#5]
On intel architectures, you can't use the 51st mantissa bit, giving you 8 tags instead of 16.

<img width="1026" alt="image" src="https://github.com/user-attachments/assets/822dd0e8-2725-4df1-8d40-9867b44e6400">
<img width="483" alt="Screenshot 2024-08-13 at 12 58 28 PM" src="https://github.com/user-attachments/assets/cd691844-b929-48ac-bd90-6a2ba30a46a4">

Source: https://www.intel.com/content/www/us/en/content-details/786447/floating-point-reference-sheet-for-intel-architecture.html

**Comment by ethanuppal** [comment]
Another explanation from [_Crafting Interpreters_](https://craftinginterpreters.com/optimization.html#nan-boxing):

<img width="597" alt="image" src="https://github.com/user-attachments/assets/943893a3-f1e0-4693-a48f-00b1b29a356c">

**Comment by CraftSpider** [comment]
Interesting, I didn't know about that. I'll look into fixing it when I have some free time.

**Comment by CraftSpider** [comment]
Hm, based on that spec, intel reserves the negative qNaN with all-zero payload as Real Indefinite - this library *already* will never store non-float data as that bit pattern. It preserves the sign of an incoming NaN value, and so if you feed it a Real Indefinite on Intel, you'll actually get a Real Indefinite back. If you feed it a different negative NaN you'll also get a Real Indefinite back to be fair, so it may be worth giving up sign-preservation here, but I feel losing half your tags is a bad way to solve the problem.

The way Crafting Interpreters does it, by always setting the 50th bit, is a simpler way of avoiding it, but likely was chosen for ease of implementation over actual necessity.

**Comment by ethanuppal** [comment]
Oh, good catch!

**Comment by CraftSpider** [comment]
I'll probably close this issue, unless you believe negative NaN being coerced to RInd is likely to cause problems.

As a little detail, this actually came out of a mix of implementation decisions - the library actually avoids situations which would have an all-zero payload by saying that there's no such thing as an all-zero tag. Instead of giving up a bit entirely, it says tags can have either sign, but the payload bits must be in the range of `1..8` instead of `0..8`. Thus tags always have at least one bit set in the payload. So, both positive and negative qNaN of all-zero payloads are left to floats, which happens to overlap with Intel's RInd definition. This ends up giving us 14 tags instead of 16, though you can argue from a bit-twiddling perspective that we've simply reserved the `+0` and `-0` tags to mean 'NaN' and 'Negative NaN'.

**Comment by ethanuppal** [comment]
Sounds good! I guess I was pretty lazy when reading the code as to not think hard enough about whether it would avoid this problem. Feel free to close
